// <auto-generated />
using System;
using GtfsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GtfsApi.Migrations
{
    [DbContext(typeof(GtfsContext))]
    [Migration("20240325180128_MovingToLaptop")]
    partial class MovingToLaptop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("GtfsApi.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fk_parentAgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fk_parentAgencyId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("GtfsApi.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("GtfsApi.Models.CalendarDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExceptionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("GtfsApi.Models.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FareId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("GtfsApi.Models.FareAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fk_fareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GtfsFareId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("TransferDuration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Transfers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fk_fareId");

                    b.ToTable("FareAttributesTbl");
                });

            modelBuilder.Entity("GtfsApi.Models.FeedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedEndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedPublisherName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedPublisherUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedStartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fk_agencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fk_agencyId");

                    b.ToTable("FeedInfoTbl");
                });

            modelBuilder.Entity("GtfsApi.Models.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("GtfsApi.Models.ParentAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParentAgencies");
                });

            modelBuilder.Entity("GtfsApi.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fk_agencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GtfsAgencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fk_agencyId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("GtfsApi.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DistanceTraveled")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShapeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ShapePtLat")
                        .HasColumnType("REAL");

                    b.Property<float>("ShapePtLon")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("GtfsApi.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("GtfsApi.Models.StopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DropoffType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_stopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_tripId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PickupType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StopSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fk_stopId");

                    b.HasIndex("Fk_tripId");

                    b.ToTable("StopTimes");
                });

            modelBuilder.Entity("GtfsApi.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_fromStopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_toStopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinTransferTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransferType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fk_fromStopId");

                    b.HasIndex("Fk_toStopId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("GtfsApi.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_routeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GtfsRouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Headsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShapeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fk_routeId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GtfsApi.Models.Agency", b =>
                {
                    b.HasOne("GtfsApi.Models.ParentAgency", "ParentAgency")
                        .WithMany()
                        .HasForeignKey("Fk_parentAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentAgency");
                });

            modelBuilder.Entity("GtfsApi.Models.FareAttributes", b =>
                {
                    b.HasOne("GtfsApi.Models.Fare", "Fare")
                        .WithMany()
                        .HasForeignKey("Fk_fareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("GtfsApi.Models.FeedInfo", b =>
                {
                    b.HasOne("GtfsApi.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("Fk_agencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("GtfsApi.Models.Route", b =>
                {
                    b.HasOne("GtfsApi.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("Fk_agencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("GtfsApi.Models.StopTime", b =>
                {
                    b.HasOne("GtfsApi.Models.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("Fk_stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GtfsApi.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("Fk_tripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GtfsApi.Models.Transfer", b =>
                {
                    b.HasOne("GtfsApi.Models.Stop", "FromStop")
                        .WithMany()
                        .HasForeignKey("Fk_fromStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GtfsApi.Models.Stop", "ToStop")
                        .WithMany()
                        .HasForeignKey("Fk_toStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStop");

                    b.Navigation("ToStop");
                });

            modelBuilder.Entity("GtfsApi.Models.Trip", b =>
                {
                    b.HasOne("GtfsApi.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("Fk_routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
